---
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "kvstore/vplugin/supersecret"
    #avp.kubernetes.io/secret-engine: "kv2" 
type: Opaque
stringData:
  username: <username>
  password: <password>
