---
apiVersion: v1
kind: Secret
metadata:
  # change comment to re-trigger load of new credentials version - test 12
  name: example-secret
  annotations:
    # ACHTUNG: Path + "data"
    avp.kubernetes.io/path: "kvstore/data/vplugin/supersecret"
    #avp.kubernetes.io/path: "kvstore/vplugin/supersecret"
type: Opaque
stringData:
  username: <username>
  password: <password>
